# Generated by Django 4.2.2 on 2023-06-28 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samsApp', '0002_student_batch_teachernotification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentnotification',
            name='course',
        ),
    ]
